spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

validations-dto:
  user-request:
    email-format: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    password-format: ^(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).+$
    password-min-size: ^.{8,}$

users:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080